# Generated by Django 4.0.4 on 2023-01-05 04:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Expenditure', '지출'), ('Income', '수입')], max_length=25, verbose_name='AccountBookType name')),
            ],
            options={
                'db_table': 'ACCOUNT_BOOK_TYPE',
            },
        ),
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, help_text='Price is only a positive number greater than 0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967294)], verbose_name='AccountBook Price')),
                ('dt', models.DateTimeField(auto_now=True, verbose_name='AccountBook Time')),
                ('memo', models.CharField(blank=True, max_length=30, verbose_name='AccountBook Memo')),
                ('is_satisfied', models.BooleanField(default=False, help_text='If you satisfied true, otherwise false', verbose_name='Satisfaction Check')),
                ('account_book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.accountbooktype', verbose_name='AccountBook Type')),
            ],
            options={
                'db_table': 'ACCOUNT_BOOK',
            },
        ),
    ]
