# Generated by Django 4.0.4 on 2023-01-05 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='AccountBook Category'),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='recorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='AccountBook Recorder'),
        ),
    ]
