# Generated by Django 4.0.4 on 2023-01-05 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Custom check')),
                ('account_book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbook.accountbooktype', verbose_name='AccountBook Type in Category')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Category Writer')),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
    ]
