# Generated by Django 4.0.4 on 2023-01-05 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nickname'),
        ),
    ]
